version: '3'
services:
  app:
    build:
      context: ../../
      dockerfile: docker/dev/Dockerfile
    image: ${PROJECT_NAME}-image
    container_name: ${PROJECT_NAME}-container
    restart: always
    ports:
      - ${WEB_PORT}:80
    volumes:
      - ../../src:/var/www/html
    networks:
      - global_networks
networks:
  global_networks:
    name: ${PROJECT_NAME}-network
    driver: bridge
