version: '3'
services:
  app:
    build:
      context: ../../
      dockerfile: docker/dev/Dockerfile
    image: docker-image-ma
    container_name: docker-image-ma
    ports:
      - '8001:80'
    volumes:
      - ../../src:/var/www/html
    networks:
      global_networks:

networks:
  global_networks:
